// models/Category.js
const mongoose = require('mongoose');

const CategorySchema = new mongoose.Schema({
    // Based on src/data/categories.ts
    // Use the id generated by MongoDB (_id) instead of defining 'id'
    name: {
        type: String,
        required: [true, 'Category name is required'],
        unique: true,
        trim: true,
    },
    description: {
        type: String,
        required: [true, 'Description is required'],
    },
    heroImage: {
        type: String,
        required: [true, 'Hero image URL is required'],
    },
    icon: { // Emoji or identifier
        type: String,
        required: [true, 'Icon is required'],
    },
    // productCount is not stored, it's calculated dynamically
    createdAt: {
        type: Date,
        default: Date.now,
    },
    updatedAt: {
        type: Date,
        default: Date.now,
    },
});

// Middleware to update `updatedAt`
CategorySchema.pre('save', function(next) {
  this.updatedAt = Date.now();
  next();
});

// Indexes
CategorySchema.index({ name: 1 });

module.exports = mongoose.model('Category', CategorySchema); // Collection name will be 'categories'